# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MiliCssApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MiliCssApp
	pod 'MJExtension'
	pod 'MJRefresh'
	pod 'Masonry'	
	pod 'MBProgressHUD'
	pod 'AFNetworking'
	pod 'SDWebImage'
	pod 'IQKeyboardManager'
	pod 'SDCycleScrollView'
 	pod 'SDAutoLayout'
	pod 'UMCCommon'
    	pod 'UMCSecurityPlugins'
	pod 'UMCShare/UI'
	pod 'UMCShare/Social/WeChat'
	pod 'UMCShare/Social/QQ'
  target 'MiliCssAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MiliCssAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
